sudo: required

services:
  - docker

before_script:
  - docker build -t alphanganga/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e "CI=true" alphanganga/client-test npm run test -- --coverage

after_success:
  - docker build -t alphanganga/multi-client ./client
  - docker build -t alphanganga/multi-nginx ./nginx
  - docker build -t alphanganga/multi-server ./server
  - docker build -t alphanganga/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_ID --password-stdin
  # Push all this version to dockerhub
  - docker push alphanganga/multi-client
  - docker push alphanganga/multi-nginx
  - docker push alphanganga/multi-server
  - docker push alphanganga/multi-worker
