version: 2
jobs:
  build:
    docker:
      context: ../client
      dockerfile: Dockerfile.dev

    working_directory: ~/app

    steps:
      - checkout
      - run:
        name: Run test
        command: docker run -e "CI=true" alphanganga/client-test npm run test -- --coverage
